config/routes.rb
  Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end
    post '/rate' => 'rater#create', :as => 'rate'
    root to: 'home#index'

    devise_for :users, path: "", controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: 'omniauth_callbacks'}, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout', edit: 'dashboard'}

    devise_scope :user do
      get "logout" => "users/sessions#destroy"
  end

  resources :grounds do
      collection do
        get 'search'
        post 'booking_initialize'
        get 'my_booked_grounds'
        post 'publish_ground'
    end
    member do
        get 'ground_details'
    end
end

resources :bookings do
    collection do
        post 'payment_success'
        post 'payment_fail'
        put 'request_for_cancel'
    end
end

get 'profile' => 'home#profile'
get 'about' => 'home#about_us'
get 'service' => 'home#service'
get 'faq' => 'home#faq'
get 'contact' => 'home#contact'
get 'terms' => 'home#terms'
get 'contact_mail' => 'home#contact_mail'

get 'newly_added_ground' => 'home#newly_added_ground'
get 'cancelation_request' => 'home#cancelation_request'
get 'transaction_history' => 'home#transaction_history'
get 'cancel_bookings/index'
get 'cancel_bookings/new'

put 'cancel_bookings/request_approved'
put 'cancel_bookings/request_discard'

mount Commontator::Engine => '/commontator'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  def base_uri
    root_path(self)
  end

  PAYU_PARAMS = {
      key: 'gtKFFx',
      salt: 'eCwWELxi',
      surl: 'http://localhost:3000/bookings/payment_success',
      furl: "#{Rails.application.routes.url_helpers.root_path}bookings/payment_fail",
      bankcode: 'payuw',
      pg: 'wallet'
  }
  # PAYU = ["gtKFFx", "eCwWELxi","http://localhost:3000/bookings/payment_success",
  #         "#{Rails.application.routes.url_helpers.root_path}bookings/payment_fail","payu_paisa"]
  belongs_to :user
  has_many :Booking_times
end


# <%= f.hidden_field :key, value: Post::PAYU[:key], name: "key" %>
# <%= f.hidden_field :salt, value: Post::PAYU[:salt], name: "salt" %>
# <%= f.text_field :txnid, value: Post::PAYU[:txnid], name: "txnid" %>
# <%= f.text_field :amount, value: Post::PAYU[:amount], name: "amount" %>
# <%= f.text_field :productinfo, value: Post::PAYU[:productinfo], name: "productinfo" %>
# <%= f.hidden_field :surl ,value: Post::PAYU[:surl], name: "surl" %>
# <%= f.hidden_field :furl, value: Post::PAYU[:furl], name: "furl" %>

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user! #, except: [:search]
  load_resource only: [:show, :create ,:update, :destroy, :edit]
  PER_PAGE = 5


  def index
    @bookings = BookingTime.where(person_id: current_user.id)
  end

  def show
  end

  # GET /grounds/new
  def new
    @booking = Booking.new
  end

  # GET /grounds/1/edit
  def edit
      
  end

  # POST /grounds
  # POST /grounds.json
  def create
    @booking = booking.new(booking_params)
    @booking.user = current_user if current_user.has_role? :member
    

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grounds/1
  # PATCH/PUT /grounds/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grounds/1
  # DELETE /grounds/1.json
  def destroy
    if @booking.destroy
      respond_to do |format|
        format.html { redirect_to grounds_url, notice: 'Booking was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def request_for_cancel
    slot_id = params[:slot_id].to_i
    slot = BookingTime.find(params[:slot_id].to_i)
    slot.update(cancelation_status: "requested for cancelation")
    ground_id = slot.ground_details.id
    CancelBooking.create(user_id: current_user.id, ground_id: ground_id, booking_time_id: slot_id, description: params[:reason])
    respond_to do |format|
      format.html { redirect_to bookings_path, notice: 'you are requested successfully.' }
      format.json { head :no_content }
    end
  end

  def payment_success
    @status = params[:status]
    @transaction_id = params[:txnid]
    @amount = params[:amount]
    @net_amount_debit = params[:net_amount_debit]
    @bank_ref_num = params[:bank_ref_num]
    @email = params[:email]
    Transaction.create(user_id: current_user.id, status: @status, transaction_id: @transaction_id, amount_debit: @net_amount_debit, bank_ref_num: @bank_ref_num)
    UserMailer.transaction_success(current_user, @transaction_id, @amount).deliver
  end

  def payment_fail
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :cancel, :slot_ids[])
    end

end

app/views/bookings/index.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>My Bookings</li>
        </ul>
      </section>
      <section class="user-profile">
        <div class="row">
          <%= render :partial => 'grounds/side_bar' %>
          <div class="col-md-9">
            <h2 class="user-profile__title">My bookings</h2>
            <hr>
            <% if @bookings.present? %>
              <% @bookings.each do |b|%>
                <div class="col-md-12">
                  <div class="btn btn-info">
                  <h3>Booked slot: <%= b.slot %>
                  (<span><%= b.booking_date.date_of_booking%></span>)</h3>
                  </div>
                  <br>
                  <div class="">
                    <div class="col-md-12">
                      <div>
                        <h4>ground :<%= b.ground_details.name %></h4>
                      </div>
                    </div>
                    <br>
                    <div class="col-md-12">
                      <div>
                        <h4>address :<%= b.ground_details.address %></h4>
                      </div>
                    </div>
                    <br>
                    <div class="col-md-12">
                      <div>
                        <h4>price :<%= b.slot_price %></h4>
                      </div>
                    </div>
                    <br>
                  </div>
                  <% if !b.cancelation_status.nil?%>
                    <%= b.cancelation_status %>
                  <% else %>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#cancel_booking_<%= b.id%>">Click to send cancel request</button>
                  <% end %>
                  <hr>
                </div>
                <div class="modal fade" id="cancel_booking_<%= b.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">request for cancel booking <%= b.slot%> on <%= b.booking_date.date_of_booking%></h4>
                      </div>
                      <div class="modal-body">
                      <div class="user-form">
                        <%= form_tag(request_for_cancel_bookings_path, :method=>'put', :remot => true) do %>
                          <%= hidden_field_tag :slot_id, b.id%>
                          <div class="field-input">
                            <label>Reason for cancel slot</label>
                            <%= text_area_tag "reason", '', class: "form-control"%>
                          </div>
                          <br>
                          <%= submit_tag "click to request", class: 'btn btn-primary' %>
                        <%end%>
                      </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        
                        <!-- <button type="submit" class="btn btn-primary">Save changes</button> -->
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4>Currently you don't have any booking...!!!!</h4>
            <% end %>
            <hr>
            <br>      
            <%= link_to "go to home page", root_path ,  :class => 'awe-btn awe-btn-1 awe-btn-medium cancle' %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/bookings/payment_fail.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <!--Breakcrumb-->
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>Payment status</li>
        </ul>
      </section>
      <section class="user-profile">
        <div class="row">
          <%= render :partial => 'grounds/side_bar' %>
          <div class="col-md-9">
            <h2 class="user-profile__title">payment faliler</h2>
            <hr>
            <div class="user-form">
              <div class="row">
                <div class="col-md-12">
                  <div class="hotel-list-cn clearfix">
                    <%# if @cancel_bookings.present? %>
                    <%# @cancel_bookings.each do |cancel_booking| %>
                    <div class="hotel-list-item">
                      <figure class="hotel-img float-left">
                        <a href="#" title="">
                          
                        </figure>
                        <div class="hotel-text">
                          <div class="hotel-name">
                           
                          </div>
                          <hr>
                          <div class="">
                            
                          </div>
                          <hr>
                          <div class="hotel-star-address">
                            <address class="hotel-address">
                              
                            </address>
                          </div>
                          <hr>
                          <p>
                            
                          </p>
                          <!-- <hr class="hr"> -->
                          <div class="">
                            <span class="price old-price"></span>
                            <span class="price special-price"><h4></h4></span>
                          </div>
                        </div>
                        <hr>
                      </div>
                      <%# end %>

                      <%# else %>
                      <hr>
                        currenly you don't have any cancellation..!!!
                      <hr>
                      <%# end %>
                    </div>
                    <%= link_to 'go back', root_path, :class => 'awe-btn awe-btn-1 awe-btn-medium' %>
                  </div> 
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>

app/views/bookings/payment_success.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <!--Breakcrumb-->
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>Payment status</li>
        </ul>
      </section>
      <!--End Breakcrumb-->

      <section class="user-profile">
        <div class="row">
          <%= render :partial => 'grounds/side_bar' %>
          <div class="col-md-9">
            <h2 class="user-profile__title">payment success</h2>
            <hr>
            <div class="user-form">
              <div class="row">
                <div class="col-md-12">
                  <div class="hotel-list-cn clearfix">
                    <div class="hotel-list-item">
                      <div>
                        Status : <%= @status %>
                      </div>
                      <br>

                      <div>
                        Transaction id : <%= @transaction_id %>
                      </div>
                      <br>

                      <div>
                        Amount : <%= @amount %>
                      </div>
                      <br>

                      <div>
                        Net amount debit : <%= @net_amount_debit %>
                      </div>
                      <br>

                      <div>
                        Bank ref num : <%= @bank_ref_num %>
                      </div>
                      <br>

                      <div>
                        Email : <%= @email %>
                      </div>
                      <br>
                    </div>
                    <%= link_to 'go back', '/bookings', :class => 'awe-btn awe-btn-1 awe-btn-medium' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>