config/routes.rb
  Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end
    post '/rate' => 'rater#create', :as => 'rate'
    root to: 'home#index'

    devise_for :users, path: "", controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: 'omniauth_callbacks'}, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout', edit: 'dashboard'}

    devise_scope :user do
      get "logout" => "users/sessions#destroy"
  end

  resources :grounds do
      collection do
        get 'search'
        post 'booking_initialize'
        get 'my_booked_grounds'
        post 'publish_ground'
    end
    member do
        get 'ground_details'
    end
end

resources :bookings do
    collection do
        post 'payment_success'
        post 'payment_fail'
        put 'request_for_cancel'
    end
end

get 'profile' => 'home#profile'
get 'about' => 'home#about_us'
get 'service' => 'home#service'
get 'faq' => 'home#faq'
get 'contact' => 'home#contact'
get 'terms' => 'home#terms'
get 'contact_mail' => 'home#contact_mail'

get 'newly_added_ground' => 'home#newly_added_ground'
get 'cancelation_request' => 'home#cancelation_request'
get 'transaction_history' => 'home#transaction_history'
get 'cancel_bookings/index'
get 'cancel_bookings/new'

put 'cancel_bookings/request_approved'
put 'cancel_bookings/request_discard'

mount Commontator::Engine => '/commontator'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! , only: [:profile]
  before_filter :is_admin?

  def index
  end

  def profile
  	
  end

  def about_us
  	
  end

  def service
  	
  end

  def faq
  	
  end

  def contact
  	
  end

  def contact_mail
    name = params[:name]
    email = params[:email]
    message = params[:message]
    UserMailer.contact_mail(name, email, message).deliver
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'successfully contacted to spotmyarena.' }
      format.json { head :no_content }
    end
  end

  def newly_added_ground
    @added_grounds = Ground.where("created_at >= ? AND publish = ?", 1.week.ago.utc, false).order("created_at DESC")
  end

  def cancelation_request
    @cancelation_requestes = CancelBooking.where("created_at >= ?", 1.week.ago.utc).order("created_at DESC")
  end

  def transaction_history
    @transaction_history = Transaction.where("created_at >= ?", 1.week.ago.utc).order("created_at DESC")
  end

  def is_admin?
    redirect_to admin_root_path if (current_admin_user)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn about-page bg-white clearfix">
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">            
          <li>About us</li>
        </ul>
      </section>
      <!-- End Breakcrumb -->
      <!-- About -->
      <section class="about-cn clearfix">
        
        <div class="about-text">
          <h1>ABOUT US&nbsp;</h1>
          <div class="about-description">
            <p>
              SpotMyArena aims to provide free online booking service for sports arena.
            </p>
            <p>
              SpotMyArena is on a mission to take sports to the next level. It not only aims to provide hassle free booking solution but also wants to ensure superb customer satisfaction.
            </p>
            <p>
              Today party, clubs, malls etc have taken a priority in our lives. It’s time to give SPORTS a shot. Just book on Spot My Arena and enjoy the moment with friends, family and YOURSELF.
            </p>
          </div>
        </div>
      </section>
      <!-- End About -->
      <!-- Team -->
      <section class="team">
        <div class="team-head">
          <h2></h2>
          <p>
            
          </p>
        </div>
        <div class="team-group row">
          <!-- Team Item -->
          <div class="team-item col-xs-6 col-md-3">
            <figure>

              <%= image_tag("gi1.jpg") %>
            </figure>
            <h3></h3>
            <span></span>
          </div>
          <!-- End Team Item -->
          <!-- Team Item -->
          <div class="team-item col-xs-6 col-md-3">
            <figure>
              <!-- <img src="images/team/img-2.jpg" alt=""> -->
              <%= image_tag "gi2.jpg", class: "" %>
            </figure>
            <h3></h3>
            <span></span>
          </div>
          <!-- End Team Item -->
          <!-- Team Item -->
          <div class="team-item col-xs-6 col-md-3">
            <figure>
              <!-- <img src="images/team/img-3.jpg" alt=""> -->
              <%= image_tag "gi3.jpg", class: "" %>
            </figure>
            <h3></h3>
            <span></span>
          </div>
          <!-- End Team Item -->
          <!-- Team Item -->
          <div class="team-item col-xs-6 col-md-3">
            <figure>
              <!-- <img src="images/team/img-4.jpg" alt=""> -->
              <%= image_tag "gi5.JPG", class: "" %>
            </figure>
            <h3></h3>
            <span></span>
          </div>
          <!-- End Team Item -->
        </div>
      </section>
      <!-- End Team -->
      <!-- Twitter -->
      <!-- End Twitter -->


    </div>
  </div>
</div>

app/views/home/cancelation_request.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <!--Breakcrumb-->
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>Cancelation requests</li>
        </ul>
      </section>
      <!--End Breakcrumb-->

      <section class="user-profile">
        <div class="row">
          <%= render :partial => 'grounds/side_bar' %>
          <div class="col-md-9">
            <h2 class="user-profile__title">Cancelation requests</h2>
            <hr>
            <div class="user-form">
              <div class="row">
                <div class="col-md-12">
                  <div class="hotel-list-cn clearfix">
                    <% if @cancelation_requestes.count > 0 %>
                        <% @cancelation_requestes.each do |cancel_booking| %>
                            <div class="hotel-list-item">
                              <div id="request">
                                <h4>user:  <%= cancel_booking.requestd_uer%></h4>
                              </div>
                             
                              <div>
                                <h4>ground: <%= cancel_booking.ground_name.name%></h4>
                              </div>
                              <div>
                                <h4>address: <%= cancel_booking.ground_name.address%></h4>
                              </div>
                              <div>
                                <h4>slot: <%= cancel_booking.booking_time%> <span> (<%= cancel_booking.booking_date%>)</span></h4>
                              </div>
                              
                              <div>
                                <h4>reason: <%= cancel_booking.description %></h4>
                              </div>
                              <hr>
                              <% if cancel_booking.approved? %>
                                Status: &nbsp<p>request approved</p>
                              <% elsif cancel_booking.discard? %>
                                Status: &nbsp<p>request discard</p>
                                Reason: <p><%= cancel_booking.response_message%></p>
                              <% else%>
                              <%= link_to "approved", cancel_bookings_request_approved_path(cancel_booking_id: cancel_booking.id, ground: cancel_booking.ground_name.name, booking_date: cancel_booking.booking_date, slot: cancel_booking.booking_time ), method: :put, remote: true, class: "btn btn-success"%>&nbsp
                              <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#cancel_request_<%= cancel_booking.id%>">Click discard request</button>
                              <% end %>
                              <hr>

                              <div class="modal fade" id="cancel_request_<%= cancel_booking.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                      <h4 class="modal-title" id="myModalLabel">reject requet from <%= cancel_booking.requestd_uer %></h4>
                                    </div>
                                    <div class="modal-body">
                                    <div class="user-form">
                                      <%= form_tag(cancel_bookings_request_discard_path, :method=>'put', :remot => true) do %>
                                        <%= hidden_field_tag :cancel_booking_id, cancel_booking.id%>
                                        <%= hidden_field_tag :slot, cancel_booking.booking_time%>
                                        <%= hidden_field_tag :booking_date, cancel_booking.booking_date%>
                                        <%= hidden_field_tag :ground, cancel_booking.ground_name.name%>
                                        <div class="field-input">
                                          <label>Reason for rejection</label>
                                          <%= text_area_tag "reason", '', class: "form-control"%>
                                        </div>
                                        <br>
                                        <%= submit_tag "click to submit", class: 'btn btn-primary' %>
                                      <%end%>
                                    </div>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                        <% end %>
                    <% else %>
                        <hr>
                        currenly you don't have any cancellation..!!!
                        <hr>
                    <% end %>
                  </div>
                  <%= link_to 'go back', root_path, :class => 'awe-btn awe-btn-1 awe-btn-medium' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<style type="text/css">
#request{  
  background: palegreen none repeat scroll 0 0;
  height: 25px;
  text-align: center;
  width: 100%;
}
</style>

app/views/home/contact.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn about-page bg-white clearfix">

      <!-- Breakcrumb -->
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          
          <li>Contact us</li>
        </ul>
      </section>
      <!-- End Breakcrumb -->
      <!-- About -->
      <section class="about-cn clearfix">
        
        <div class="about-text">
          <h1>CONTACT US&nbsp;</h1>
          <div class="about-description">
            <p>
              <h3>Email should be sent to</h3>
            </p>
            <p>
              <h2><%= image_tag "email.png", class: "", size: "50" %><a href="#"> helpdesk.spotmyarena@gmail.com</a></h2>
            </p>
          </div>
          <hr>
          <div class="about-description">
            <h3>Connect with social networks&nbsp;</h3>
            <p>
              <h3><a href="#"><%= image_tag "f.png", class: "", size: "50" %><a>FACEBOOK</h3>
            </p>
            <p>
              <h3><a href="#"><%= image_tag "t.png", class: "", size: "50" %><a>TWITTER</h3>
            </p>
            <p>
              <h3><a href="#"><%= image_tag "gplus.png", class: "", size: "50" %><a>GOOGLE plus</h3>
            </p>
            <p>
              <h3><a href="#"><%= image_tag "blog.png", class: "", size: "50" %><a>BLOG</h3>
            </p>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/home/faq.html.erb
<div class="main">
    <div class="container">
      <div class="main-cn about-page bg-white clearfix">
        <section class="breakcrumb-sc">
          <ul class="breadcrumb arrow">
            <li>FAQ</li>
          </ul>
        </section>
        <section class="about-cn clearfix"> 
          <div class="about-text">
            <h1>FAQ&nbsp;</h1>
            <div class="about-description">
            <ul>
              <hr>
              <li>
              <p>
               <h4><b> Why use SpotMyArena instead of calling up the clubs? </b></h4>
              </p>
              </li>
              <li>
              <p>
              <h4>
                Remember calling up clubs and arenas for finding available slots, rushing to the venue for ensuring you get the court, painstakingly specifying that you had called and booked the court. You have none of that with SpotMyArena. With SpotMyArena, you get to choose your arena, your date, your slot, and make the payment online. In short, we ensure that you get hassle free entertainment and spend your precious time in your favorite courts while we take care of your bookings.
              </h4>
              </p>
              </li>
              <br>
              <hr>
              <li>
              <p>
               <h4><b> What is the cancellation and refund policy of SpotMyArena ? </b></h4>
              </p>
              </li>
              <li>
              <p>
              <h4>
                Our Cancellation Fee is as follows ­                                              Upto 1 week before the booked slot ­ 10% Less  than 1 week and upto 3 days before the booked slot ­ 20% Less than 3 days and upto 24 hrs before the booked slot ­ 40% Less than 24 hours and upto 8 hrs before the booked slot ­ 60% Less than 8 hours before the booked slot ­  No  refund.

              </h4>
              </p>
              </li>
              <br>
              <hr>
              <li>
              <p>
               <h4><b> Do I need to pay amount at court ?</b></h4>
              </p>
              </li>
              <li>
              <p>
                <h4>
                  No, SpotMyArena gives you a cashless, hassle free sporting experience you can pay onlince once and then need not pay anything at the clubs.
                </h4>
              </p>
              </li>
              <br>
              <hr>
            </ul> 
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
        

app/views/home/index.html.erb
<section class="banner">
  <!--Background-->
  <div class="bg-parallax bg-1"></div>
  <!--End Background-->
  <div class="container">
    <!-- Banner Content -->
    <div class="banner-cn">
      <!-- Logo -->
      <div class="logo-banner text-center">
        <%= link_to root_path do %>
            <%= image_tag('logo-banner.png') %>
        <% end %>
      </div>
      <!-- Logo -->
      <!-- Category Singer -->
      <div class="category-singer clearfix">
        <div class="cate-singer-icon float-left">
          <h2>GROUND</h2>
          <%= image_tag 'icon-cruise.png' %>
          <!--<img src="assets/icon-cruise.png" alt="">-->
        </div>
        <p>Bridging the gap between<span>U</span>and<span>Sport</span></p>
      </div>
      <!-- End Category Singer -->
      <!-- Form Search -->
      <div class="form-cn form-cruise">
        <h2>Book Your Ground In 30 Seconds</h2>

        <div class="form-search clearfix">
          <%= form_tag search_grounds_path, :method => 'get' do %>
          <div class="form-field field-select field-lenght">
            <div class="">
              <!-- <span>Select City</span> -->
              <%= select_tag :city, options_for_select(Ground::CITY, params[:city]), include_blank: false , class: "select1"%>
            </div>
          </div>
          <div class="form-field field-select field-lenght">
            <div class="">
              <!-- <span>Ground Type</span> -->
              <%= select_tag :category, options_for_select(Ground::CATEGORY, params[:category]), include_blank: false, class: "select1"%>
            </div>
          </div>
          
          <div class="form-field field-select field-lenght">
            <div class="">
              <!-- <span>Location</span> -->
              <%= select_tag :area, options_for_select(Ground::AREA, params[:area]), include_blank: false, class: "select1"%>
            </div>
          </div>

          <div class="form-field field-date">
            <%= text_field_tag :date,(params[:date] or Date.today), class: 'field-input calendar-input', placeholder: "Check in" %>               
          </div>

          <div class="form-submit">
            <%= submit_tag "Search", :name => 'search_grounds', class: "awe-btn awe-btn-medium awe-search" %>
          </div>
          <% end %>
        </div>
      </div>
      <!-- End Form Search -->
    </div>
    <!-- End Banner Content -->
  </div>
</section>
<!-- ======================================================================about -->
<section class="destinations">

  <!-- Title -->
  <div class="title-wrap">
    <div class="container">
      <div class="travel-title float-left">
        <h2 id="destinations"></h2>
      </div>
    </div>
  </div>
  <div class="main">
    <div class="container">
      <div class="main-cn about-page bg-white clearfix">

        <!-- Breakcrumb -->
        <section class="breakcrumb-sc">
          <ul class="breadcrumb arrow">
            
            <li>About us</li>
          </ul>
        </section>
        <!-- End Breakcrumb -->
        <!-- About -->
        <section class="about-cn clearfix">
          
          <div class="about-text">
            <h1>ABOUT US&nbsp;</h1>
            <div class="about-description">
              <p>
                <h4>SpotMyArena aims to provide free online booking service for sports arena.</h4>
              </p>
              <br>
              <p>
                <h4>SpotMyArena is on a mission to take sports to the next level. It not only aims to provide hassle free booking solution but also wants to ensure superb customer satisfaction.</h4>
              </p>
              <br>
              <p>
                <h4>Today party, clubs, malls etc have taken a priority in our lives. It’s time to give SPORTS a shot. Just book on Spot My Arena and enjoy the moment with friends, family and YOURSELF.</h4>
              </p>
            </div>
          </div>
        </section>
        <!-- End About -->
        <!-- Team -->
        <section class="team">
          <div class="team-head">
            <h2></h2>
            <p>
              
            </p>
          </div>
          <div class="team-group row">
            <!-- Team Item -->
            <div class="team-item col-xs-6 col-md-3">
              <figure>

                <%= image_tag("gi1.jpg") %>
              </figure>
              <h3></h3>
              <span></span>
            </div>
            <!-- End Team Item -->
            <!-- Team Item -->
            <div class="team-item col-xs-6 col-md-3">
              <figure>
                <!-- <img src="images/team/img-2.jpg" alt=""> -->
                <%= image_tag "gi2.jpg", class: "" %>
              </figure>
              <h3></h3>
              <span></span>
            </div>
            <!-- End Team Item -->
            <!-- Team Item -->
            <div class="team-item col-xs-6 col-md-3">
              <figure>
                <!-- <img src="images/team/img-3.jpg" alt=""> -->
                <%= image_tag "gi3.jpg", class: "" %>
              </figure>
              <h3></h3>
              <span></span>
            </div>
            <!-- End Team Item -->
            <!-- Team Item -->
            <div class="team-item col-xs-6 col-md-3">
              <figure>
                <!-- <img src="images/team/img-4.jpg" alt=""> -->
                <%= image_tag "gi5.JPG", class: "" %>
              </figure>
              <h3></h3>
              <span></span>
            </div>
            <!-- End Team Item -->
          </div>
        </section>
        <!-- End Team -->
        <!-- Twitter -->
        <!-- End Twitter -->


      </div>
    </div>
  </div>
</section>
  <!-- End Title -->
<!-- =============================================================== service -->
<section class="sales">

  <!-- Title -->
  <div class="title-wrap">
    <div class="container">
      <div class="travel-title float-left">
        <h2 id="sales"></h2>
      </div>
    </div>
  </div>
  <div class="main">
    <div class="container">
      <div class="main-cn about-page bg-white clearfix">
        <section class="breakcrumb-sc">
          <ul class="breadcrumb arrow">
            <li>Service</li>
          </ul>
        </section>
        <section class="about-cn clearfix">
          
          <div class="about-text">
            <h1>SERVICE&nbsp;</h1>
            <div class="about-description">
              <p>
                <h3><%= image_tag "booking.png", class: "", size: "50" %> Hassle Free booking</h3>  
              </p>
              <br>
              <p>
                <h3><%= image_tag "secure.png", class: "", size: "50" %> Secure Payment </h3>
              </p>
              <br>
              <p>
                <h3> <%= image_tag "feedback.png", class: "", size: "50" %> Constructive feedback mechanism </h3> 
              </p>
              <br>
              <p>
               <h3> <%= image_tag "24hour.png", class: "", size: "50"%> 24*7 Customer Service </h3>
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</section>
  <!-- ===========================================================================FAQ -->
 
<section class="magazine">

  <!-- Title -->
  <div class="title-wrap">
    <div class="container">
      <div class="travel-title float-left">
        <h2 id="magazine"></h2>
      </div>
    </div>
  </div>
  <div class="main">
    <div class="container">
      <div class="main-cn about-page bg-white clearfix">
        <section class="breakcrumb-sc">
          <ul class="breadcrumb arrow">
            <li>FAQ</li>
          </ul>
        </section>
        <section class="about-cn clearfix"> 
          <div class="about-text">
            <h1>FAQ&nbsp;</h1>
            <div class="about-description">
            <ul>
              <hr>
              <li>
              <p>
               <h4><b> Why use SpotMyArena instead of calling up the clubs? </b></h4>
              </p>
              </li>
              <li>
              <p>
              <h4>
                Remember calling up clubs and arenas for finding available slots, rushing to the venue for ensuring you get the court, painstakingly specifying that you had called and booked the court. You have none of that with SpotMyArena. With SpotMyArena, you get to choose your arena, your date, your slot, and make the payment online. In short, we ensure that you get hassle free entertainment and spend your precious time in your favorite courts while we take care of your bookings.
              </h4>
              </p>
              </li>
              <br>
              <hr>
              <li>
              <p>
               <h4><b> What is the cancellation and refund policy of SpotMyArena ? </b></h4>
              </p>
              </li>
              <li>
              <p>
              <h4>
                Our Cancellation Fee is as follows ­                                              Upto 1 week before the booked slot ­ 10% Less  than 1 week and upto 3 days before the booked slot ­ 20% Less than 3 days and upto 24 hrs before the booked slot ­ 40% Less than 24 hours and upto 8 hrs before the booked slot ­ 60% Less than 8 hours before the booked slot ­  No  refund.

              </h4>
              </p>
              </li>
              <br>
              <hr>
              <li>
              <p>
               <h4><b> Do I need to pay amount at court ?</b></h4>
              </p>
              </li>
              <li>
              <p>
                <h4>
                  No, SpotMyArena gives you a cashless, hassle free sporting experience you can pay onlince once and then need not pay anything at the clubs.
                </h4>
              </p>
              </li>
              <br>
              <hr>
            </ul> 
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</section>
<!-- ==============================================================================contact --> 
<section class="contact-page">
  <div class="title-wrap">
    <div class="container">
      <div class="travel-title float-left">
        <h2 id="contact-maps"></h2>
      </div>
    </div>
  </div>
  <div class="main">
    <div class="container">
      <div class="main-cn about-page bg-white clearfix">
        <section class="breakcrumb-sc">
          <ul class="breadcrumb arrow">
            <li>Contact us</li>
          </ul>
        </section>
        <section class="about-cn clearfix">
          <div class="about-text">
            <h1>CONTACT US&nbsp;</h1>
            <hr>
          </div>
          
          <div class="about-description">
            <div class="contact-cn">
            <h2>We are always in touch</h2>
            <ul>
              <li>
                <%= image_tag "icon-maker-contact.png"%>
                Delhi
              </li>
              <li>
                <%= image_tag "icon-email.png"%>
                <p>helpdesk.spotmyarena@gmail.com</p>
              </li>
            </ul>
            <div class="form-contact">
              <%= form_tag(contact_mail_path, :method=>'get') do %>
              
                <div class="form-field">
                  <label for="name">Name <sup>*</sup></label>
                  <%= text_area_tag "name", '', class: "field-input"%>
                </div>
                <div class="form-field">
                  <label for="email">Email <sup>*</sup></label>
                  <%= text_area_tag "email", '', class: "field-input"%>
                </div>
                <div class="form-field form-field-area">
                  <label for="message">Message <sup>*</sup></label>
                  <%= text_area_tag "message", '', class: "field-input"%>
                </div>
                <div class="form-field text-center">
                  <%= submit_tag "click to submit", class: 'btn btn-success' %>
                <%end%>
                </div>
                <div id="contact-content">
                </div>
              
            </div>
          </div>
          <div>
            <div class="follow-us">
                <h4>Follow us</h4>
                <div class="follow-group">
                  <a href="" title=""><i class="fa fa-google-plus"></i></a>
                  <a href="" title=""><i class="fa fa-facebook"></i></a>
                  <a href="" title=""><i class="fa fa-twitter"></i></a>
                  <a href="" title=""><i class="fa fa-instagram"></i></a>
                </div>
              </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</section>
<!-- ======================================================================= term -->

    <!-- End Confidence and Subscribe  -->


 <style type="text/css">

.select1 {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    border-color: white pink green white;
    border-image: none;
    border-style: ridge none dotted ridge;
    border-width: thin;
    font-family: "Open sans";
    height: 45px;
    position: relative;
    width: 100%;
}
 </style>       

app/views/home/newly_added_ground.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <!--Breakcrumb-->
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>Newly added grounds</li>
        </ul>
      </section>
      <!--End Breakcrumb-->

      <section class="user-profile">
        <div class="row">
          <%= render :partial => 'grounds/side_bar' %>
          <div class="col-md-9">
            <h2 class="user-profile__title">Newly added grounds</h2>
            <hr>
            <div class="user-form">
              <div class="row">
                <div class="col-md-12">
                  <div class="hotel-list-cn clearfix">
                    <% if @added_grounds.present? %>
                    <% @added_grounds.each do |ground| %>
                      <div>
                        
                          <div class="hotel-name">
                            <h3><%= ground.name%><h3>
                          </div>
                          <div>
                            Ground type: <%= ground.category %>
                          </div>
                          <div class="">
                            Owner name: <%= ground.user.name %>
                          </div>
                          <div class="">
                            Owner contact: <%= ground.phone %>
                          </div>
                          <div class="">
                            Address: <%= ground.address %>
                          </div>
                          <br>
                          <div class="">
                            <%= link_to "Click to publish", publish_ground_grounds_path(id: ground.id), method: :post, remote: true, class: "btn btn-success publish_#{ground.id}"%>
                          </div>
                        <hr>
                      </div>
                      <% end %>

                      <% else %>
                      <hr>
                        this week ground owner's can't added any ground!!!
                      <hr>
                      <% end %>
                    </div>
                    <%= link_to 'go back', root_path, :class => 'awe-btn awe-btn-1 awe-btn-medium' %>
                  </div> 
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>