config/routes.rb
  Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :admin_user do
    get '/admin/logout', :to => 'active_admin/devise/sessions#destroy'
  end
    post '/rate' => 'rater#create', :as => 'rate'
    root to: 'home#index'

    devise_for :users, path: "", controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations", omniauth_callbacks: 'omniauth_callbacks'}, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout', edit: 'dashboard'}

    devise_scope :user do
      get "logout" => "users/sessions#destroy"
  end

  resources :grounds do
      collection do
        get 'search'
        post 'booking_initialize'
        get 'my_booked_grounds'
        post 'publish_ground'
    end
    member do
        get 'ground_details'
    end
end

resources :bookings do
    collection do
        post 'payment_success'
        post 'payment_fail'
        put 'request_for_cancel'
    end
end

get 'profile' => 'home#profile'
get 'about' => 'home#about_us'
get 'service' => 'home#service'
get 'faq' => 'home#faq'
get 'contact' => 'home#contact'
get 'terms' => 'home#terms'
get 'contact_mail' => 'home#contact_mail'

get 'newly_added_ground' => 'home#newly_added_ground'
get 'cancelation_request' => 'home#cancelation_request'
get 'transaction_history' => 'home#transaction_history'
get 'cancel_bookings/index'
get 'cancel_bookings/new'

put 'cancel_bookings/request_approved'
put 'cancel_bookings/request_discard'

mount Commontator::Engine => '/commontator'

end

app/models/ground.rb
class Ground < ActiveRecord::Base
  include ApplicationHelper
  TIME_SLOT = ["12:00 AM","01:00 AM", "02:00 AM", "03:00 AM", "04:00 AM", "05:00 AM", "06:00 AM", "07:00 AM", "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM", "11:00 PM"]
  CATEGORY = ["Tabel Tennis", "BadMinton", "Cricket Nets",  "Snooker", "Tennis"]
  CITY =['Delhi', 'Channei']
  AREA =['Connaught Place', 'Chanakyapuri', 'Delhi Cantonment', 'Vasant Vihar', 'North Delhi', 'Narela', 'Model Town', 'Narela', 'Alipur', 'North West Delhi', 'Kanjhawala', 'Rohini', 'Kanjhawala', 'Saraswati Vihar', 'West Delhi', 'Rajouri Garden', 'Patel Nagar', 'Punjabi Bagh', 'South West Delhi', 'Dwarka', 'Najafgarh', 'Kapashera', 'South Delhi', 'Saket', 'Hauz Khas', 'Mehrauli', 'South East Delhi', 'Defence Colony', 'Lajpat Nagar', 'Kalkaji', 'Sarita Vihar', 'Central Delhi', 'Daryaganj', 'Karol Bagh', 'Kotwali', 'Civil Lines', 'North East Delhi', 'Seelampur', 'Yamuna Vihar', 'Karawal Nagar', 'Shahdara', 'Seemapuri', 'Vivek Vihar', 'East Delhi', 'Preet Vihar', 'Gandhi Nagar', 'Mayur Vihar']
  WEEKDAY = [["Rs. 100", 100.to_f], ["Rs. 150", 150.to_f], ["Rs. 170", 170.to_f], ["Rs. 200", 200.to_f], ["Rs. 220", 220.to_f], ["Rs. 230", 230.to_f], ["Rs. 240", 240.to_f], ["Rs. 250", 250.to_f], ["Rs. 260", 260.to_f], ["Rs. 270", 270.to_f], ["Rs. 280", 280.to_f], ["Rs. 300", 300.to_f], ["Rs. 320", 320.to_f], ["Rs. 330", 330.to_f], ["Rs. 340", 340.to_f], ["Rs. 350", 350.to_f], ["Rs. 360", 360.to_f], ["Rs. 370", 370.to_f], ["Rs. 380", 380.to_f], ["Rs. 400", 400.to_f]]
  WEEKEND = [["Rs. 100", 100.to_f], ["Rs. 150", 150.to_f], ["Rs. 170", 170.to_f], ["Rs. 200", 200.to_f], ["Rs. 220", 220.to_f], ["Rs. 230", 230.to_f], ["Rs. 240", 240.to_f], ["Rs. 250", 250.to_f], ["Rs. 260", 260.to_f], ["Rs. 270", 270.to_f], ["Rs. 280", 280.to_f], ["Rs. 300", 300.to_f], ["Rs. 320", 320.to_f], ["Rs. 330", 330.to_f], ["Rs. 340", 340.to_f], ["Rs. 350", 350.to_f], ["Rs. 360", 360.to_f], ["Rs. 370", 370.to_f], ["Rs. 380", 380.to_f], ["Rs. 400", 400.to_f]]
  belongs_to :user
  has_many :booking_dates, :dependent => :destroy
  has_many :ground_attachments, :dependent => :destroy

  validates :weekday_price, :format => {:with => /\A\d+(?:\.\d{0,2})?\z/}, :numericality => {:greater_than => 0, :message => "only allow digits"}
  validates :weekend_price, :format => {:with => /\A\d+(?:\.\d{0,2})?\z/}, :numericality => {:greater_than => 0, :message => "only allow digits"}

  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :area
  #validates_numericality_of :value, :on => :create
  acts_as_commontable

  ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'

  accepts_nested_attributes_for :ground_attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :booking_dates, reject_if: :all_blank, allow_destroy: true

  after_create :set_merchant_id

  attr_accessor :add_booking_dates, :add_closing_dates, :closing_times, :special_closing_date, :special_closing_times, :slot_ids

  def self.search(category, city, area, date)
    if category.present? && city.present? && area.present? && date.present?
      results = self.joins(:booking_dates).where('city LIKE ? AND category LIKE ? AND area LIKE ? AND booking_dates.date_of_booking = ?', "%#{city}%", "%#{category}%", "%#{area}%","%#{date}%")
      results.where("publish = ?", true).order("created_at DESC")
      if results.blank?
        Ground.where("publish = ?", true).order("created_at DESC")
      end
    else
      Ground.where("publish = ?", true).order("created_at DESC")
    end
  end

  def set_date_and_time(add_booking_dates)
    ground_id = self.id
    booking_dates = add_booking_dates.split(",").map { |e| e.to_date }
    if booking_dates.present?
      booking_dates.each do |d|
        BookingDate.create(date_of_booking: d, ground_id: self.id, status: true)
      end
      booking_dates1 = self.booking_dates
      timeslots = ["12:00 AM", "01:00 AM", "02:00 AM", "03:00 AM", "04:00 AM", "05:00 AM", "06:00 AM", "07:00 AM", "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM", "11:00 PM"]

      booking_dates1.each do |d|
        timeslots.each do |t|
          BookingTime.create(slot: t, status: true, booking_date_id: d.id)
        end
      end
    end
  end

  def update_date_and_time(add_booking_dates, add_closing_dates, closing_times)
    ground_id = self.id
    add_booking_dates = add_booking_dates.split(",").map { |e| e.to_date } if add_booking_dates.present?
    add_closing_dates = add_closing_dates.split(",").map { |e| e.to_date } if add_closing_dates.present?
    closing_times = closing_times.reject(&:empty?) if closing_times.present?
    timeslots = ["12:00 AM", "01:00 AM", "02:00 AM", "03:00 AM", "04:00 AM", "05:00 AM", "06:00 AM", "07:00 AM", "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM", "11:00 PM"]
    ground_dates = self.booking_dates
    if add_closing_dates.present?
      add_closing_dates.each do |cd|
        ground_dates.each do |d|
          d.destroy if d.date_of_booking == cd
        end
      end
    else
      return false
    end
    if add_booking_dates.present?
      add_booking_dates.each do |bd|
        add_date = BookingDate.create(date_of_booking: bd, ground_id: self.id, status: true)
        timeslots.each do |t|
          BookingTime.create(slot: t, status: true, booking_date_id: add_date.id)
        end
      end
    else
      return false
    end

    if closing_times.present?
      closing_times.each do |ct|
        self.booking_dates.each do |date|
          date.booking_times.each do |time|
            time.update(status: false) if time.slot == ct
          end
        end
      end
    else
      return false
    end    
  end

  def update_special_closing_time(special_closing_date, special_closing_times)
    special_closing_date = special_closing_date.to_date
    special_closing_times = special_closing_times.reject(&:empty?)
    current_booking_dates = self.booking_dates
    select_date = current_booking_dates.where(date_of_booking: special_closing_date).first
    if special_closing_date.present?
      special_closing_times.each do |sc|       
        if !select_date.nil?
          select_date.booking_times.each do |ct|
            ct.destroy if ct.slot == sc && ct.booked == false
          end
        else
          return false
        end
      end
    else
      return false
    end
  end

  def ground_status
    if self.status == true
      "Available"
    elsif self.status == false
      "Not-available"
    end
  end


  def day_price
    # (self.weekday_price * 10)/100
    self.weekday_price
  end

  def end_price
    # (self.weekend_price * 10)/100
    self.weekend_price
  end

  def set_merchant_id
    id = generate_unique_id
    self.update(merchant_id: id)
  end

  def slots
    self.booking_dates.collect { |c| c.booking_times.map { |e| e if e.booked } }.flatten.compact
  end

  protected

  def self.payu(user, transaction_id, amount, ground)
    Digest::SHA2.new(512).hexdigest("#{PAYU_CONFIG['key']}|#{transaction_id}|#{amount}|#{ground}|#{user.first_name}|#{user.email}|#{PAYU_CONFIG['salt']}")
  end
end


# <%= f.hidden_field :hash, value: @post.hash("#{Post::PAYU[:key]}|#{Post::PAYU[:txnid]}|#{Post::PAYU[:amount]}|#{Post::PAYU[:productinfo]}|#{Post::PAYU[:firstname]}|#{Post::PAYU[:email]}|||||||||||#{Post::PAYU[:salt]}"), name: "hash" %>

app/controllers/grounds_controller.rb
  class GroundsController < ApplicationController
    include ApplicationHelper
    before_action :authenticate_user! , except: [:search, :ground_details]
    before_action :update_slotes, only: :booking_initialize
    load_resource only: [:show, :create ,:update, :destroy, :edit]
    PER_PAGE = 5
    def search
      return @grounds = Ground.all
    	category = params[:category]
    	city = params[:city]
    	area = params[:area]
    	date = params[:date].to_date
    	@grounds = Kaminari.paginate_array(Ground.search(category, city, area, date)).page(params[:page] || 1).per(PER_PAGE)

    end

    def index
      @grounds = current_user.grounds if current_user.present? #&& current_user.has_role? "ground_owner"

    end

    def show
      @booking = Booking.new
    end
    
    def ground_details
      @ground = Ground.find(params[:id])
    end

    # GET /grounds/new
    def new
      @ground = Ground.new
      #@ground_attachment = @ground.ground_attachments.build
    end

    # GET /grounds/1/edit
    def edit
      @added_dates = @ground.booking_dates.map{|e| e.date_of_booking}
      @closing_times = ["12:00 AM","01:00 AM", "02:00 AM", "03:00 AM", "04:00 AM", "05:00 AM", "06:00 AM", "07:00 AM", "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM", "11:00 PM"]
    end

    # POST /grounds
    # POST /grounds.json
    def create
      @ground = Ground.new(ground_params)
      @ground.user = current_user if current_user.has_role? :ground_owner


      respond_to do |format|
        if @ground.save
          @ground.set_date_and_time(params[:ground][:add_booking_dates])
          format.html { redirect_to @ground, notice: 'ground was successfully added.' }
          format.json { render :show, status: :created, location: @ground }
        else
          format.html { render :new }
          format.json { render json: @ground.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /grounds/1
    # PATCH/PUT /grounds/1.json
    def update
      respond_to do |format|
        if @ground.update(ground_params)
          @ground.update_date_and_time(params[:ground][:add_booking_dates], params[:ground][:add_closing_dates], params[:ground][:closing_times])
          @ground.update_special_closing_time(params[:ground][:special_closing_date], params[:ground][:special_closing_times])
          #@ground.update_date_and_time(ground_params[:start_date], ground_params[:end_date])
          format.html { redirect_to @ground, notice: 'ground was successfully updated.' }
          format.json { render :show, status: :ok, location: @ground }
        else
          format.html { render :edit }
          format.json { render json: @ground.errors.messages, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /grounds/1
    # DELETE /grounds/1.json
    def destroy
      if @ground.destroy
        respond_to do |format|
          format.html { redirect_to grounds_url, notice: 'ground was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    end

    
    def booking_initialize
      unless params[:slot_ids].split("{:value=>\"\"}").reject(&:empty?).blank?
        @price = params[:book_a].to_i
        ids =  params[:slot_ids].split(',').reject(&:empty?)
        @booked_event = []
        ids.each do |i|
          slot = BookingTime.find_by(id: i.to_i)
          @booked_event << slot
        end
        @booking = Booking.new
        @transaction_id = transaction_id
        @ground = Ground.find(params[:ground]).name
        @Total_price = @booked_event.map{|t| t.booking_date.weekend_day? ? t.booking_date.ground.end_price : t.booking_date.ground.day_price}.inject(:+)
        @hash = Ground.payu(current_user, @transaction_id, @Total_price, @ground)
        @booked_event
      else
        @ground = Ground.find(params[:ground])
        redirect_to ground_details_ground_path(@ground), notice: "please select slots"
      end
    end


    def publish_ground
     ground = Ground.find(params[:id])
     ground.update(publish: true)
      respond_to do |format|
        format.js { flash[:notice] = "published successfully"}
      end
    end

    #user section
    def my_booked_grounds
      @grounds = current_user.grounds.map{|e| e if e.booking_dates.map{|e| e.booking_times.map{|e| e.booked}}}
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_ground
        @ground = ground.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def ground_params
        params.require(:ground).permit(:start_date, :end_date, :name, :city, :area, :pincode, :address, :status, :category, :weekend_price, :weekday_price, :court, :phone, :attention_message , booking_dates_attributes: [:id, :date_of_booking, :status, :ground_id, :_destroy, booking_times_attributes: [:id, :time_of_booking, :status, :booking_date_id, :timeslot_id, :_destroy]], ground_attachments_attributes: [:id, :ground_id, :photo, :_destroy])
      end

      def update_slotes
         unless params[:slot_ids].split("{:value=>\"\"}").reject(&:empty?).blank?
          ids =  params[:slot_ids].split(',').reject(&:empty?)
          @booked_event = []
          ids.each do |i|
            slot = BookingTime.find_by(id: i.to_i)
            @booked_event << slot
          end
          @ground = Ground.find(params[:ground])
          @booked_event 
          @booked_event.each do |b|
            slot = BookingTime.find(b)
            price = slot.booking_date.weekend_day? ? slot.booking_date.ground.end_price : slot.booking_date.ground.day_price
            slot.update(person_id: current_user.id, booked: true, slot_price: price)
          end
        else
          @ground = Ground.find(params[:ground])
          redirect_to ground_details_ground_path(@ground), notice: "please select slots"
        end
      end
  end

app/helpers/grounds_helper.rb
module GroundsHelper
end

app/views/grounds/_booking_date_fields.html.erb
<div class="nested-fields">
  <%= f.label :Date %><br>
  <%= f.text_field :date_of_booking, class: 'field-input-calendar field-date-ground datepicker', placeholder: "Booking date"%>
  
  <%= f.check_box :status, {checked: true} %>&nbsp;&nbsp;<%= f.label 'available' %><br>
  <div class="field-input">
    <table id="tasks">
      <%= f.fields_for :booking_times, :wrapper => false do |booking_time| %>
      <tr class="fields">
        <%= render 'booking_time_fields', f: booking_time %>
      </tr>
      <% end %>
    </table>
    <%= link_to_add_association 'Add time slot', f, :booking_times, class: "btn1 time-slot" %>
  </div>
  <%= link_to_remove_association "Remove date", f, class: "btn-remove rmv"%>
  <!-- <div class="clearfix"></div> -->
</div>



<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({
      dateFormat: "dd/mm/yy",
      showOtherMonths: true,
      selectOtherMonths: true
    });
  });
</script>

app/views/grounds/_booking_time_fields.html.erb
<div class="nested-fields">
    <%= f.select :timeslot_id, Timeslot.all.map{|e| [e.slot, e.id ]}, {:placeholder => "select time slot"}, class: 'input-select-time', include_blank: false %>
    <%= f.check_box :status, {checked: true} %>&nbsp;&nbsp;<%= f.label 'Available' %>
    <%= link_to_remove_association "remove time slot", f, class: "btn-remove"%>
    <div class="clrfix"></div>
</div>

app/views/grounds/_side_bar.html.erb
<div class="col-md-3">
  <div class="user-profile__header">
    <h4><%= current_user.name %></h4>
    <span>Member Since <%= current_user.created_at.strftime("%b %Y")%></span>
    <h3>ID: <%= current_user.member_id%></h3>
    <p>
      <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar_url %>
      <% else %>
      <%= image_tag('avatar.png') %>
      <% end %>
    </p>
  </div>
  <ul class="user-profile__navigation">

    <% if current_user.has_role? :admin %>
      <li class="current">
        <%= link_to newly_added_ground_path do %>
        newly added grounds<%= image_tag('icon-cart.png') %>
        <% end %>
      </li>
      <li class="current">
        <%= link_to cancelation_request_path do %>
        Cancelation requetes<%= image_tag('icon-cart.png') %>
        <% end %>
      </li>
       <li class="current">
        <%= link_to transaction_history_path do %>
        Transaction history<%= image_tag('icon-cart.png') %>
        <% end %>
      </li>
    <% end %>
    <% if current_user.has_role? :ground_owner %>
    <li class="current">
      <%= link_to grounds_path do %>
      My grounds<%= image_tag('icon-cart.png') %>
      <% end %>
    </li>
    <li class="current">
      <%= link_to new_ground_path do %>
      new ground entry<%= image_tag('icon-hotel.png') %>
      <% end %>
    </li>
    <li class="current">
      <%= link_to my_booked_grounds_grounds_path do %>
      My booked ground<%= image_tag('icon-service-12.png') %>
      <% end %>
    </li>
    <% elsif current_user.has_role? :member %>
    <li class="current">
      <%= link_to bookings_path do %>
      My bookings<%= image_tag('icon-cart.png') %>
      <% end %>
    </li>
    <li class="current">
      <%= link_to cancel_bookings_index_path do %>
      My canceled bookings<%= image_tag('icon-cart.png') %>
      <% end %>
    </li>
    <% else %>
    
    <% end %>  
    <li class="current">
      <%= link_to profile_path do %>
      My profile <%= image_tag('icon-user.png') %>
      <% end %>
    </li>
    <li class="current">
      <%= link_to edit_user_registration_path do %>
      Setting <%= image_tag('icon-setting.png') %>
      <% end %>
    </li>

    <li class="current">
      <%= link_to destroy_user_session_path, method: :delete do %>
      logout <%= image_tag('icon-back.png') %>
      <% end %>
    </li>
  </ul>
</div>


<script type="text/javascript">
  $(document).ready(fnReadyIndex());
  function fnReadyIndex () {
    $("li>a").on("click", function() {
     $("li.current").removeClass("current");
     $(this).parent().addClass("current");
   });
  }
</script>

app/views/grounds/booking_initialize.html.erb
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <!--Breakcrumb-->
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>Booking</li>
        </ul>
      </section>
      <!--End Breakcrumb-->
      <section class="element-sc">
        <!-- Order Table -->
        <hr>
        <div class="col-md-12">
          <div class="alert alert-info">Having trouble booking slots? Call our executive to book instantly
            +919093057565
          </div>
        </div>
        <hr>

        <div class="col-md-8 col-xs-12">

          <%= form_for @booking, url: PAYU_CONFIG['url'], :method => :post do |f| %>
              <form id="payu_form">
                <%= f.hidden_field :key, value: PAYU_CONFIG['key'], name: "key" %>
                <%= f.hidden_field :salt, value: PAYU_CONFIG['salt'], name: "salt" %>
                <%= f.hidden_field :bankcode, value: PAYU_CONFIG['bankcode'], name: "bankcode" %>
                <%= f.hidden_field :pg, value: PAYU_CONFIG['pg'], name: "pg" %>
                <%= f.hidden_field :surl, value: payment_success_bookings_url, name: "surl" %>
                <%= f.hidden_field :furl, value: payment_fail_bookings_url, name: "furl" %>
                <%= f.hidden_field :hash, value: @hash, name: "hash" %>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Transaction id</label>
                    <%= f.text_field :txnid, value: @transaction_id, name: "txnid", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Total amount</label>
                    <%= f.text_field :amount, value: @Total_price, name: "amount", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Ground name</label>
                    <%= f.text_field :productinfo, value: @ground, name: "productinfo", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Your first name</label>
                    <%= f.text_field :firstname, value: current_user.first_name, name: "firstname", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Your Email</label>
                    <%= f.text_field :email, value: current_user.email, name: "email", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Your Phone</label>
                    <%= f.text_field :phone, value: current_user.mobile, name: "phone", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-12">
                  <h2>Payment Method</h2>
                  <input required="" type="radio" id="pp-radio-payment-1" name="payment_method" value="PAYU" checked="checked">
                  <label for="pp-radio-payment-1"><span></span>PayU</label>

                </div>
                <br>
                <hr>
                <div class="col-md-12">
                  <button type="submit" class="btn btn-primary payu">Go to payment</button>
                </div>
                <hr>
              </form>
          <% end %>
        </div>

        <div class="col-md-4 col-md-12">
          <h2>Order Summary</h2>
          <hr>
          <div class="order-info">
            <h3 class="text-center" style="color: blue;"><%= @ground %></h3>
            <hr>
            <p style="margin-bottom:5px !important;"><strong>Selected Slots</strong>:
              <% @booked_event.each do |b| %>
                  <!-- <span id="slots_sum"></span></p> -->
                <div class="slot_button"><%= b.slot %>
                  <h6>(<%= b.booking_date.date_of_booking.strftime("%d %b %Y") %>)</h6></div>
            <% end %>
            <!-- <h6 style="color:#696f78 !important;"><center>(Wooden Court)</center></h6> -->
            <hr>
            <table>
              <tbody>
              <tr>
                <td><h5><strong>Total:</strong></h5></td>
                <td class="btn-info btn">Rs. <%= @Total_price %></td>
              </tr>
              <hr>
              <tr class="st_os">
                <td>(Service Charge)</td>
                <td class="price_os"> + Rs.0</td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-md-12">
          <div class="divider"></div>

        </div>
        </p>
      </section>
    </div>
  </div>
</div>
</div>
<!-- End Main -->

<style type="text/css">
    .slot_button {
        -moz-user-select: none;
        background: palegreen none repeat scroll 0 0;
        border: 1px solid transparent;
        border-radius: 4px;
        color: gray !important;
        cursor: pointer;
        display: inline-block;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857;
        margin: 2px;
        padding: 0 3px;
        text-align: center;
        text-decoration: none !important;
        vertical-align: middle;
        white-space: nowrap;
    }

    .form-group {
        pointer-events: none;
        cursor: default;
    }
</style>

app/views/grounds/edit.html.erb
<%= render :partial => 'form' %>

app/views/grounds/index.html.erb
<section class="sub-banner">
  <div class="bg-parallax bg-1"></div>
  <div class="logo-banner text-center">
    <%= link_to root_path do %>
    <%= image_tag "logo-banner.png", class: "" %>
    <% end %>
  </div>
</section>
<div class="main">
  <div class="container">
    <div class="main-cn element-page bg-white clearfix">
      <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
          <li>My ground page</li>
        </ul>
      </section>
      <section class="user-profile">
        <div class="row">
          <%= render :partial => 'grounds/side_bar' %>

          <div class="col-md-9">
            <h2 class="user-profile__title">My grounds page</h2>
            <hr>
            <div class="user-form">
              <div class="row">
                <div class="col-md-12">
                  <div class="hotel-list-cn clearfix">
                    <% if @grounds.present? %>
                    <% @grounds.each do |ground| %>
                    <div class="hotel-list-item">
                      <figure class="hotel-img float-left">
                        <a href="#" title="">
                          <%= link_to ground_path(ground) do %>
                          <% if ground.ground_attachments.present? %>
                          <%= image_tag ground.ground_attachments.last.photo_url, size: "200" %>
                          <% else %>
                          <%= image_tag 'logo-banner.png' %>
                          <%end%>
                          <% end %>
                        </figure>
                        <div class="hotel-text">
                          <div class="hotel-name">
                            <%= link_to ground_path(ground) do %>
                            <%= ground.name %>
                            <% end %>
                          </div>
                          <hr>
                          <div class="">
                            <a class= "btn btn-default btn-sm"><%= ground.category%></a>
                            <%= link_to 'Click to edit info', edit_ground_path(ground), :class => 'btn btn-info pull-right'%>
                          </div>
                          <hr>
                          <div class="hotel-star-address">
                            <address class="hotel-address">
                              <%= ground.area %>
                            </address>
                          </div>
                          <hr>
                          <p>
                            <%= ground.attention_message %>
                          </p>
                          <div class="">
                            <span class="price old-price"></span>
                            <span class="price special-price"><h4>Rs. <%= ground.weekend_price %>/<%= ground.weekday_price %><h6>(Weekend/Weekday)</h6></h4></span>
                          </div>
                        </div>
                        <hr>
                      </div>
                      <% end %>
                      <% end %>
                    </div>
                    <%= link_to 'go back', root_path, :class => 'awe-btn awe-btn-1 awe-btn-medium' %>
                  </div> 
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  <!-- End Main -->

app/views/grounds/new.html.erb
<%= render :partial => 'form' %>

app/views/grounds/publish_ground.js.erb
alert("published successfully");
window.location.reload();